import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Wrapper from "./wrapper";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

// This default export is required in a new `pages/_app.js` file.
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
          {children} <Toaster position="top-right" />
        </Wrapper>
      </body>
    </html>
  );
}
